// Code generated by github.com/hasura/ndc-sdk-go/v2/cmd/hasura-ndc-go, DO NOT EDIT.
package functions

import (
	"context"
	"encoding/json"
	"github.com/hasura/ndc-sdk-go/v2/connector"
	"github.com/hasura/ndc-sdk-go/v2/schema"
	"github.com/hasura/ndc-sdk-go/v2/utils"
	"go.opentelemetry.io/otel/trace"
	"hasura-ndc.dev/ndc-go/types"
	"log/slog"
	"slices"
)

// FromValue decodes values from map
func (j *BatchCalculateRiskArguments) FromValue(input map[string]any) error {
	var err error
	j.Claims, err = utils.DecodeObjectValue[[]ClaimData](input, "claims")
	if err != nil {
		return err
	}
	return nil
}

// FromValue decodes values from map
func (j *CalculateClaimRiskArguments) FromValue(input map[string]any) error {
	var err error
	j.Claim, err = utils.DecodeObjectValue[ClaimData](input, "claim")
	if err != nil {
		return err
	}
	return nil
}

// FromValue decodes values from map
func (j *ClaimData) FromValue(input map[string]any) error {
	var err error
	j.ClaimAmount, err = utils.GetFloat[float64](input, "claim_amount")
	if err != nil {
		return err
	}
	j.ClaimID, err = utils.GetString(input, "claim_id")
	if err != nil {
		return err
	}
	j.ClaimType, err = utils.GetString(input, "claim_type")
	if err != nil {
		return err
	}
	j.MemberID, err = utils.GetString(input, "member_id")
	if err != nil {
		return err
	}
	j.ProviderID, err = utils.GetNullableString(input, "provider_id")
	if err != nil {
		return err
	}
	j.ServiceDate, err = utils.GetString(input, "service_date")
	if err != nil {
		return err
	}
	return nil
}

// FromValue decodes values from map
func (j *GenerateClaimSummaryArguments) FromValue(input map[string]any) error {
	var err error
	j.Claim, err = utils.DecodeObjectValue[ClaimData](input, "claim")
	if err != nil {
		return err
	}
	return nil
}

// ToMap encodes the struct to a value map
func (j ClaimData) ToMap() map[string]any {
	r := make(map[string]any)
	r["claim_amount"] = j.ClaimAmount
	r["claim_id"] = j.ClaimID
	r["claim_type"] = j.ClaimType
	r["member_id"] = j.MemberID
	r["provider_id"] = j.ProviderID
	r["service_date"] = j.ServiceDate

	return r
}

// ToMap encodes the struct to a value map
func (j ClaimProcessResult) ToMap() map[string]any {
	r := make(map[string]any)
	r["approved"] = j.Approved
	r["approved_amount"] = j.ApprovedAmount
	r["claim_id"] = j.ClaimID
	r["processing_time"] = j.ProcessingTime
	r["rejection_reason"] = j.RejectionReason
	r["status"] = j.Status

	return r
}

// ToMap encodes the struct to a value map
func (j ClaimSummary) ToMap() map[string]any {
	r := make(map[string]any)
	r["claim_id"] = j.ClaimID
	r["member_id"] = j.MemberID
	r["net_amount"] = j.NetAmount
	r["status"] = j.Status
	r["summary"] = j.Summary
	r["tax_amount"] = j.TaxAmount
	r["total_amount"] = j.TotalAmount

	return r
}

// ToMap encodes the struct to a value map
func (j RiskScore) ToMap() map[string]any {
	r := make(map[string]any)
	r["claim_id"] = j.ClaimID
	r["factors"] = j.Factors
	r["risk_level"] = j.RiskLevel
	r["risk_score"] = j.RiskScore
	r["timestamp"] = j.Timestamp

	return r
}

// DataConnectorHandler implements the data connector handler
type DataConnectorHandler struct{}

// QueryExists check if the query name exists
func (dch DataConnectorHandler) QueryExists(name string) bool {
	return slices.Contains(enumValues_FunctionName, name)
}
func (dch DataConnectorHandler) Query(ctx context.Context, state *types.State, request *schema.QueryRequest, rawArgs map[string]any) (*schema.RowSet, error) {
	if !dch.QueryExists(request.Collection) {
		return nil, utils.ErrHandlerNotfound
	}
	queryFields, err := utils.EvalFunctionSelectionFieldValue(request)
	if err != nil {
		return nil, schema.UnprocessableContentError(err.Error(), nil)
	}

	result, err := dch.execQuery(context.WithValue(ctx, utils.CommandSelectionFieldKey, queryFields), state, request, queryFields, rawArgs)
	if err != nil {
		return nil, err
	}

	return &schema.RowSet{
		Aggregates: schema.RowSetAggregates{},
		Rows: []map[string]any{
			{
				"__value": result,
			},
		},
	}, nil
}

func (dch DataConnectorHandler) execQuery(ctx context.Context, state *types.State, request *schema.QueryRequest, queryFields schema.NestedField, rawArgs map[string]any) (any, error) {
	span := trace.SpanFromContext(ctx)
	logger := connector.GetLogger(ctx)
	switch request.Collection {
	case "batchCalculateRisk":

		selection, err := queryFields.AsArray()
		if err != nil {
			return nil, schema.UnprocessableContentError("the selection field type must be array", map[string]any{
				"cause": err.Error(),
			})
		}
		var args BatchCalculateRiskArguments
		parseErr := args.FromValue(rawArgs)
		if parseErr != nil {
			return nil, schema.UnprocessableContentError("failed to resolve arguments", map[string]any{
				"cause": parseErr.Error(),
			})
		}

		connector_addSpanEvent(span, logger, "execute_function", map[string]any{
			"arguments": args,
		})
		rawResult, err := FunctionBatchCalculateRisk(ctx, state, &args)

		if err != nil {
			return nil, err
		}

		connector_addSpanEvent(span, logger, "evaluate_response_selection", map[string]any{
			"raw_result": rawResult,
		})
		result, err := utils.EvalNestedColumnArrayIntoSlice(selection, rawResult)
		if err != nil {
			return nil, err
		}
		return result, nil

	case "calculateClaimRisk":

		selection, err := queryFields.AsObject()
		if err != nil {
			return nil, schema.UnprocessableContentError("the selection field type must be object", map[string]any{
				"cause": err.Error(),
			})
		}
		var args CalculateClaimRiskArguments
		parseErr := args.FromValue(rawArgs)
		if parseErr != nil {
			return nil, schema.UnprocessableContentError("failed to resolve arguments", map[string]any{
				"cause": parseErr.Error(),
			})
		}

		connector_addSpanEvent(span, logger, "execute_function", map[string]any{
			"arguments": args,
		})
		rawResult, err := FunctionCalculateClaimRisk(ctx, state, &args)

		if err != nil {
			return nil, err
		}

		if rawResult == nil {
			return nil, nil
		}
		connector_addSpanEvent(span, logger, "evaluate_response_selection", map[string]any{
			"raw_result": rawResult,
		})
		result, err := utils.EvalNestedColumnObject(selection, rawResult)
		if err != nil {
			return nil, err
		}
		return result, nil

	case "generateClaimSummary":

		selection, err := queryFields.AsObject()
		if err != nil {
			return nil, schema.UnprocessableContentError("the selection field type must be object", map[string]any{
				"cause": err.Error(),
			})
		}
		var args GenerateClaimSummaryArguments
		parseErr := args.FromValue(rawArgs)
		if parseErr != nil {
			return nil, schema.UnprocessableContentError("failed to resolve arguments", map[string]any{
				"cause": parseErr.Error(),
			})
		}

		connector_addSpanEvent(span, logger, "execute_function", map[string]any{
			"arguments": args,
		})
		rawResult, err := FunctionGenerateClaimSummary(ctx, state, &args)

		if err != nil {
			return nil, err
		}

		if rawResult == nil {
			return nil, nil
		}
		connector_addSpanEvent(span, logger, "evaluate_response_selection", map[string]any{
			"raw_result": rawResult,
		})
		result, err := utils.EvalNestedColumnObject(selection, rawResult)
		if err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, utils.ErrHandlerNotfound
	}
}

var enumValues_FunctionName = []string{"batchCalculateRisk", "calculateClaimRisk", "generateClaimSummary"}

// MutationExists check if the mutation name exists
func (dch DataConnectorHandler) MutationExists(name string) bool {
	return slices.Contains(enumValues_ProcedureName, name)
}
func (dch DataConnectorHandler) Mutation(ctx context.Context, state *types.State, operation *schema.MutationOperation) (schema.MutationOperationResults, error) {
	span := trace.SpanFromContext(ctx)
	logger := connector.GetLogger(ctx)
	ctx = context.WithValue(ctx, utils.CommandSelectionFieldKey, operation.Fields)
	connector_addSpanEvent(span, logger, "validate_request", map[string]any{
		"operations_name": operation.Name,
	})

	switch operation.Name {
	case "batchProcessClaims":

		selection, err := operation.Fields.AsArray()
		if err != nil {
			return nil, schema.UnprocessableContentError("the selection field type must be array", map[string]any{
				"cause": err.Error(),
			})
		}
		var args BatchProcessClaimsArguments
		if err := json.Unmarshal(operation.Arguments, &args); err != nil {
			return nil, schema.UnprocessableContentError("failed to decode arguments", map[string]any{
				"cause": err.Error(),
			})
		}
		span.AddEvent("execute_procedure")
		rawResult, err := ProcedureBatchProcessClaims(ctx, state, &args)

		if err != nil {
			return nil, err
		}

		connector_addSpanEvent(span, logger, "evaluate_response_selection", map[string]any{
			"raw_result": rawResult,
		})
		result, err := utils.EvalNestedColumnArrayIntoSlice(selection, rawResult)

		if err != nil {
			return nil, err
		}
		return schema.NewProcedureResult(result).Encode(), nil

	case "processClaim":

		selection, err := operation.Fields.AsObject()
		if err != nil {
			return nil, schema.UnprocessableContentError("the selection field type must be object", map[string]any{
				"cause": err.Error(),
			})
		}
		var args ProcessClaimArguments
		if err := json.Unmarshal(operation.Arguments, &args); err != nil {
			return nil, schema.UnprocessableContentError("failed to decode arguments", map[string]any{
				"cause": err.Error(),
			})
		}
		span.AddEvent("execute_procedure")
		rawResult, err := ProcedureProcessClaim(ctx, state, &args)

		if err != nil {
			return nil, err
		}

		if rawResult == nil {
			return schema.NewProcedureResult(nil).Encode(), nil
		}
		connector_addSpanEvent(span, logger, "evaluate_response_selection", map[string]any{
			"raw_result": rawResult,
		})
		result, err := utils.EvalNestedColumnObject(selection, rawResult)

		if err != nil {
			return nil, err
		}
		return schema.NewProcedureResult(result).Encode(), nil

	default:
		return nil, utils.ErrHandlerNotfound
	}
}

var enumValues_ProcedureName = []string{"batchProcessClaims", "processClaim"}

func connector_addSpanEvent(span trace.Span, logger *slog.Logger, name string, data map[string]any) {
	logger.Debug(name, slog.Any("data", data))
	attrs := utils.DebugJSONAttributes(data, utils.IsDebug(logger))
	span.AddEvent(name, trace.WithAttributes(attrs...))
}
