services:
  app_neon_postgres_1:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.neon_postgres_1
    environment:
      CONNECTION_URI: $APP_NEON_POSTGRES_1_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $APP_NEON_POSTGRES_1_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_NEON_POSTGRES_1_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_NEON_POSTGRES_1_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - "${APP_NEON_POSTGRES_1_HASURA_CONNECTOR_PORT:-5637}:8080"
