services:
  app_neon_postgres_2:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.neon_postgres_2
    environment:
      CONNECTION_URI: $APP_NEON_POSTGRES_2_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $APP_NEON_POSTGRES_2_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_NEON_POSTGRES_2_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_NEON_POSTGRES_2_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - "${APP_NEON_POSTGRES_2_HASURA_CONNECTOR_PORT:-5791}:8080"
